apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-notes
spec:
  replicas: 3

  selector:
    matchLabels:
      app: flask-notes

  template:
    metadata:
      labels:
        app: flask-notes

    spec:
      containers:
        - name: flask-notes
          image: 297165774342.dkr.ecr.us-east-1.amazonaws.com/flask-notes-devops:5
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: flask-notes-config

            - secretRef:
                name: flask-notes-secret

          readinessProbe:
            httpGet:
              path: /notes
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /notes
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

